GET http://www.localhost:8080/members

Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm51QGdtYWlsLmNvbSIsImlhdCI6MTY5NjczMzQ1OSwiZXhwIjoxNjk2NzM0ODk5fQ.lr7X5zhmdLkZA_PAZcb_85iEZRVlZjrmsygK6peqna8

###
POST http://localhost:8080/users/signin

{
    "email":"vinay@gmail.com",
    "password":"string"
}

###
POST http://localhost:8080/users/register
content-type: application/json


{
    "email": "annu@gmail.com",
    "name": "java",
    "dob": "2023-01-01",
    "aadhar": "dfjklsjfkljd234",
    "address": "kanput",
    "gender":"MALE",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": "201305",
    "pan": "jjwt233",
    "password": "string"
}
