export const FETCH_APPOINTMENT_DATA_REQUEST = "FETCH_APPOINTMENT_DATA_REQUEST";
export const FETCH_APPOINTMENT_DATA_SUCCES = "FETCH_APPOINTMENT_DATA_SUCCES";
export const FETCH_APPOINTMENT_DATA_FAILURE = "FETCH_APPOINTMENT_DATA_FAILURE";
