

POST http://localhost:8080/users/register
content-type: application/json


{
    "email": "kava@gmail.com",
    "name": "java",
    "dob": "2023-01-01",
    "aadhar": "dfjklsjfkljd234",
    "address": "kanput",
    "gender":"MALE",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": "201305",
    "pan": "jjwt233",
    "password": "string"
}


###
POST https://covisafeplus-production-417c.up.railway.app/appointments/14e73044-f2b4-44aa-920f-f53368a87206/0ce64d0e-7d1c-4a69-9140-47a745a08cba

content-type: application/json


Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aW5heUBnbWFpbC5jb20iLCJpYXQiOjE2OTU4MzYyNzUsImV4cCI6MTY5NTgzNzcxNX0.j00GTc633W1sXEsTNo1Ag7acj2pAJ6mA1uj1AHJeAj4

{
    "slot": "SLOT1",
    "mobileNo": "7291971753"
}