

POST http://localhost:8080/users/register
content-type: application/json


{
    "email": "kava@gmail.com",
    "name": "java",
    "dob": "2023-01-01",
    "aadhar": "dfjklsjfkljd234",
    "address": "kanput",
    "gender":"MALE",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": "201305",
    "pan": "jjwt233",
    "password": "string"
}


###
POST http://localhost:8080/members/24c6b1c9-4521-482c-8f8a-8e83ef9757c6

content-type: application/json


Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrYXZhQGdtYWlsLmNvbSIsImlhdCI6MTY5NTY1OTc1MCwiZXhwIjoxNjk1NjYxMTkwfQ.dIuRj2Bgw33Wzhj2EfPLPSy0vRYuYDighkWODf6khcE

{
    "mobileNo": 9197533709
}
